import { readFileSync } from 'fs';

const swagger = JSON.parse(readFileSync('swagger.v1.json', 'utf8'));

// All METHOD+PATH combinations we know are covered by the routing table
const routingCoverage = new Set([
	'GET /repos/{owner}/{repo}',
	'DELETE /repos/{owner}/{repo}',
	'PATCH /repos/{owner}/{repo}',
	'GET /repos/{owner}/{repo}/actions/runners/jobs',
	'GET /repos/{owner}/{repo}/actions/runners/registration-token',
	'GET /repos/{owner}/{repo}/actions/runs',
	'GET /repos/{owner}/{repo}/actions/runs/{run_id}',
	'GET /repos/{owner}/{repo}/actions/secrets',
	'PUT /repos/{owner}/{repo}/actions/secrets/{secretname}',
	'DELETE /repos/{owner}/{repo}/actions/secrets/{secretname}',
	'GET /repos/{owner}/{repo}/actions/tasks',
	'GET /repos/{owner}/{repo}/actions/variables',
	'GET /repos/{owner}/{repo}/actions/variables/{variablename}',
	'PUT /repos/{owner}/{repo}/actions/variables/{variablename}',
	'POST /repos/{owner}/{repo}/actions/variables/{variablename}',
	'DELETE /repos/{owner}/{repo}/actions/variables/{variablename}',
	'POST /repos/{owner}/{repo}/actions/workflows/{workflowfilename}/dispatches',
	'GET /repos/{owner}/{repo}/activities/feeds',
	'GET /repos/{owner}/{repo}/archive/{archive}',
	'GET /repos/{owner}/{repo}/assignees',
	'POST /repos/{owner}/{repo}/avatar',
	'DELETE /repos/{owner}/{repo}/avatar',
	'GET /repos/{owner}/{repo}/branch_protections',
	'POST /repos/{owner}/{repo}/branch_protections',
	'GET /repos/{owner}/{repo}/branch_protections/{name}',
	'DELETE /repos/{owner}/{repo}/branch_protections/{name}',
	'PATCH /repos/{owner}/{repo}/branch_protections/{name}',
	'GET /repos/{owner}/{repo}/branches',
	'POST /repos/{owner}/{repo}/branches',
	'GET /repos/{owner}/{repo}/branches/{branch}',
	'DELETE /repos/{owner}/{repo}/branches/{branch}',
	'PATCH /repos/{owner}/{repo}/branches/{branch}',
	'GET /repos/{owner}/{repo}/collaborators',
	'GET /repos/{owner}/{repo}/collaborators/{collaborator}',
	'PUT /repos/{owner}/{repo}/collaborators/{collaborator}',
	'DELETE /repos/{owner}/{repo}/collaborators/{collaborator}',
	'GET /repos/{owner}/{repo}/collaborators/{collaborator}/permission',
	'GET /repos/{owner}/{repo}/commits',
	'GET /repos/{owner}/{repo}/commits/{ref}/status',
	'GET /repos/{owner}/{repo}/commits/{ref}/statuses',
	'GET /repos/{owner}/{repo}/commits/{sha}/pull',
	'GET /repos/{owner}/{repo}/compare/{basehead}',
	'GET /repos/{owner}/{repo}/contents',
	'POST /repos/{owner}/{repo}/contents',
	'GET /repos/{owner}/{repo}/contents/{filepath}',
	'PUT /repos/{owner}/{repo}/contents/{filepath}',
	'POST /repos/{owner}/{repo}/contents/{filepath}',
	'DELETE /repos/{owner}/{repo}/contents/{filepath}',
	'POST /repos/{owner}/{repo}/convert',
	'POST /repos/{owner}/{repo}/diffpatch',
	'GET /repos/{owner}/{repo}/editorconfig/{filepath}',
	'GET /repos/{owner}/{repo}/flags',
	'PUT /repos/{owner}/{repo}/flags',
	'DELETE /repos/{owner}/{repo}/flags',
	'GET /repos/{owner}/{repo}/flags/{flag}',
	'PUT /repos/{owner}/{repo}/flags/{flag}',
	'DELETE /repos/{owner}/{repo}/flags/{flag}',
	'GET /repos/{owner}/{repo}/forks',
	'POST /repos/{owner}/{repo}/forks',
	'GET /repos/{owner}/{repo}/git/blobs',
	'GET /repos/{owner}/{repo}/git/blobs/{sha}',
	'GET /repos/{owner}/{repo}/git/commits/{sha}',
	'GET /repos/{owner}/{repo}/git/commits/{sha}.{diffType}',
	'GET /repos/{owner}/{repo}/git/notes/{sha}',
	'POST /repos/{owner}/{repo}/git/notes/{sha}',
	'DELETE /repos/{owner}/{repo}/git/notes/{sha}',
	'GET /repos/{owner}/{repo}/git/refs',
	'GET /repos/{owner}/{repo}/git/refs/{ref}',
	'GET /repos/{owner}/{repo}/git/tags/{sha}',
	'GET /repos/{owner}/{repo}/git/trees/{sha}',
	'GET /repos/{owner}/{repo}/hooks',
	'POST /repos/{owner}/{repo}/hooks',
	'GET /repos/{owner}/{repo}/hooks/git',
	'GET /repos/{owner}/{repo}/hooks/git/{id}',
	'DELETE /repos/{owner}/{repo}/hooks/git/{id}',
	'PATCH /repos/{owner}/{repo}/hooks/git/{id}',
	'GET /repos/{owner}/{repo}/hooks/{id}',
	'DELETE /repos/{owner}/{repo}/hooks/{id}',
	'PATCH /repos/{owner}/{repo}/hooks/{id}',
	'POST /repos/{owner}/{repo}/hooks/{id}/tests',
	'GET /repos/{owner}/{repo}/issue_config',
	'GET /repos/{owner}/{repo}/issue_config/validate',
	'GET /repos/{owner}/{repo}/issue_templates',
	'GET /repos/{owner}/{repo}/issues',
	'POST /repos/{owner}/{repo}/issues',
	'GET /repos/{owner}/{repo}/issues/comments',
	'GET /repos/{owner}/{repo}/issues/comments/{id}',
	'DELETE /repos/{owner}/{repo}/issues/comments/{id}',
	'PATCH /repos/{owner}/{repo}/issues/comments/{id}',
	'GET /repos/{owner}/{repo}/issues/comments/{id}/assets',
	'POST /repos/{owner}/{repo}/issues/comments/{id}/assets',
	'GET /repos/{owner}/{repo}/issues/comments/{id}/assets/{attachment_id}',
	'DELETE /repos/{owner}/{repo}/issues/comments/{id}/assets/{attachment_id}',
	'PATCH /repos/{owner}/{repo}/issues/comments/{id}/assets/{attachment_id}',
	'GET /repos/{owner}/{repo}/issues/comments/{id}/reactions',
	'POST /repos/{owner}/{repo}/issues/comments/{id}/reactions',
	'DELETE /repos/{owner}/{repo}/issues/comments/{id}/reactions',
	'GET /repos/{owner}/{repo}/issues/pinned',
	'GET /repos/{owner}/{repo}/issues/{index}',
	'DELETE /repos/{owner}/{repo}/issues/{index}',
	'PATCH /repos/{owner}/{repo}/issues/{index}',
	'GET /repos/{owner}/{repo}/issues/{index}/assets',
	'POST /repos/{owner}/{repo}/issues/{index}/assets',
	'GET /repos/{owner}/{repo}/issues/{index}/assets/{attachment_id}',
	'DELETE /repos/{owner}/{repo}/issues/{index}/assets/{attachment_id}',
	'PATCH /repos/{owner}/{repo}/issues/{index}/assets/{attachment_id}',
	'GET /repos/{owner}/{repo}/issues/{index}/blocks',
	'POST /repos/{owner}/{repo}/issues/{index}/blocks',
	'DELETE /repos/{owner}/{repo}/issues/{index}/blocks',
	'GET /repos/{owner}/{repo}/issues/{index}/comments',
	'POST /repos/{owner}/{repo}/issues/{index}/comments',
	'POST /repos/{owner}/{repo}/issues/{index}/deadline',
	'GET /repos/{owner}/{repo}/issues/{index}/dependencies',
	'POST /repos/{owner}/{repo}/issues/{index}/dependencies',
	'DELETE /repos/{owner}/{repo}/issues/{index}/dependencies',
	'GET /repos/{owner}/{repo}/issues/{index}/labels',
	'POST /repos/{owner}/{repo}/issues/{index}/labels',
	'PUT /repos/{owner}/{repo}/issues/{index}/labels',
	'DELETE /repos/{owner}/{repo}/issues/{index}/labels',
	'DELETE /repos/{owner}/{repo}/issues/{index}/labels/{identifier}',
	'POST /repos/{owner}/{repo}/issues/{index}/pin',
	'DELETE /repos/{owner}/{repo}/issues/{index}/pin',
	'PATCH /repos/{owner}/{repo}/issues/{index}/pin/{position}',
	'GET /repos/{owner}/{repo}/issues/{index}/reactions',
	'POST /repos/{owner}/{repo}/issues/{index}/reactions',
	'DELETE /repos/{owner}/{repo}/issues/{index}/reactions',
	'DELETE /repos/{owner}/{repo}/issues/{index}/stopwatch/delete',
	'POST /repos/{owner}/{repo}/issues/{index}/stopwatch/start',
	'POST /repos/{owner}/{repo}/issues/{index}/stopwatch/stop',
	'GET /repos/{owner}/{repo}/issues/{index}/subscriptions',
	'GET /repos/{owner}/{repo}/issues/{index}/subscriptions/check',
	'PUT /repos/{owner}/{repo}/issues/{index}/subscriptions/{user}',
	'DELETE /repos/{owner}/{repo}/issues/{index}/subscriptions/{user}',
	'GET /repos/{owner}/{repo}/issues/{index}/timeline',
	'GET /repos/{owner}/{repo}/issues/{index}/times',
	'POST /repos/{owner}/{repo}/issues/{index}/times',
	'DELETE /repos/{owner}/{repo}/issues/{index}/times',
	'DELETE /repos/{owner}/{repo}/issues/{index}/times/{id}',
	'GET /repos/{owner}/{repo}/keys',
	'POST /repos/{owner}/{repo}/keys',
	'GET /repos/{owner}/{repo}/keys/{id}',
	'DELETE /repos/{owner}/{repo}/keys/{id}',
	'GET /repos/{owner}/{repo}/labels',
	'POST /repos/{owner}/{repo}/labels',
	'GET /repos/{owner}/{repo}/labels/{id}',
	'DELETE /repos/{owner}/{repo}/labels/{id}',
	'PATCH /repos/{owner}/{repo}/labels/{id}',
	'GET /repos/{owner}/{repo}/languages',
	'GET /repos/{owner}/{repo}/media/{filepath}',
	'GET /repos/{owner}/{repo}/milestones',
	'POST /repos/{owner}/{repo}/milestones',
	'GET /repos/{owner}/{repo}/milestones/{id}',
	'DELETE /repos/{owner}/{repo}/milestones/{id}',
	'PATCH /repos/{owner}/{repo}/milestones/{id}',
	'POST /repos/{owner}/{repo}/mirror-sync',
	'GET /repos/{owner}/{repo}/new_pin_allowed',
	'GET /repos/{owner}/{repo}/notifications',
	'PUT /repos/{owner}/{repo}/notifications',
	'GET /repos/{owner}/{repo}/pulls',
	'POST /repos/{owner}/{repo}/pulls',
	'GET /repos/{owner}/{repo}/pulls/pinned',
	'GET /repos/{owner}/{repo}/pulls/{base}/{head}',
	'GET /repos/{owner}/{repo}/pulls/{index}',
	'PATCH /repos/{owner}/{repo}/pulls/{index}',
	'GET /repos/{owner}/{repo}/pulls/{index}.{diffType}',
	'GET /repos/{owner}/{repo}/pulls/{index}/commits',
	'GET /repos/{owner}/{repo}/pulls/{index}/files',
	'GET /repos/{owner}/{repo}/pulls/{index}/merge',
	'POST /repos/{owner}/{repo}/pulls/{index}/merge',
	'DELETE /repos/{owner}/{repo}/pulls/{index}/merge',
	'POST /repos/{owner}/{repo}/pulls/{index}/requested_reviewers',
	'DELETE /repos/{owner}/{repo}/pulls/{index}/requested_reviewers',
	'GET /repos/{owner}/{repo}/pulls/{index}/reviews',
	'POST /repos/{owner}/{repo}/pulls/{index}/reviews',
	'GET /repos/{owner}/{repo}/pulls/{index}/reviews/{id}',
	'POST /repos/{owner}/{repo}/pulls/{index}/reviews/{id}',
	'DELETE /repos/{owner}/{repo}/pulls/{index}/reviews/{id}',
	'GET /repos/{owner}/{repo}/pulls/{index}/reviews/{id}/comments',
	'POST /repos/{owner}/{repo}/pulls/{index}/reviews/{id}/comments',
	'GET /repos/{owner}/{repo}/pulls/{index}/reviews/{id}/comments/{comment}',
	'DELETE /repos/{owner}/{repo}/pulls/{index}/reviews/{id}/comments/{comment}',
	'POST /repos/{owner}/{repo}/pulls/{index}/reviews/{id}/dismissals',
	'POST /repos/{owner}/{repo}/pulls/{index}/reviews/{id}/undismissals',
	'POST /repos/{owner}/{repo}/pulls/{index}/update',
	'GET /repos/{owner}/{repo}/push_mirrors',
	'POST /repos/{owner}/{repo}/push_mirrors',
	'POST /repos/{owner}/{repo}/push_mirrors-sync',
	'GET /repos/{owner}/{repo}/push_mirrors/{name}',
	'DELETE /repos/{owner}/{repo}/push_mirrors/{name}',
	'GET /repos/{owner}/{repo}/raw/{filepath}',
	'GET /repos/{owner}/{repo}/releases',
	'POST /repos/{owner}/{repo}/releases',
	'GET /repos/{owner}/{repo}/releases/latest',
	'GET /repos/{owner}/{repo}/releases/tags/{tag}',
	'DELETE /repos/{owner}/{repo}/releases/tags/{tag}',
	'GET /repos/{owner}/{repo}/releases/{id}',
	'DELETE /repos/{owner}/{repo}/releases/{id}',
	'PATCH /repos/{owner}/{repo}/releases/{id}',
	'GET /repos/{owner}/{repo}/releases/{id}/assets',
	'POST /repos/{owner}/{repo}/releases/{id}/assets',
	'GET /repos/{owner}/{repo}/releases/{id}/assets/{attachment_id}',
	'DELETE /repos/{owner}/{repo}/releases/{id}/assets/{attachment_id}',
	'PATCH /repos/{owner}/{repo}/releases/{id}/assets/{attachment_id}',
	'GET /repos/{owner}/{repo}/reviewers',
	'GET /repos/{owner}/{repo}/signing-key.gpg',
	'GET /repos/{owner}/{repo}/stargazers',
	'GET /repos/{owner}/{repo}/statuses/{sha}',
	'POST /repos/{owner}/{repo}/statuses/{sha}',
	'GET /repos/{owner}/{repo}/subscribers',
	'GET /repos/{owner}/{repo}/subscription',
	'PUT /repos/{owner}/{repo}/subscription',
	'DELETE /repos/{owner}/{repo}/subscription',
	'GET /repos/{owner}/{repo}/sync_fork',
	'POST /repos/{owner}/{repo}/sync_fork',
	'GET /repos/{owner}/{repo}/sync_fork/{branch}',
	'POST /repos/{owner}/{repo}/sync_fork/{branch}',
	'GET /repos/{owner}/{repo}/tag_protections',
	'POST /repos/{owner}/{repo}/tag_protections',
	'GET /repos/{owner}/{repo}/tag_protections/{id}',
	'DELETE /repos/{owner}/{repo}/tag_protections/{id}',
	'PATCH /repos/{owner}/{repo}/tag_protections/{id}',
	'GET /repos/{owner}/{repo}/tags',
	'POST /repos/{owner}/{repo}/tags',
	'GET /repos/{owner}/{repo}/tags/{tag}',
	'DELETE /repos/{owner}/{repo}/tags/{tag}',
	'GET /repos/{owner}/{repo}/teams',
	'GET /repos/{owner}/{repo}/teams/{team}',
	'PUT /repos/{owner}/{repo}/teams/{team}',
	'DELETE /repos/{owner}/{repo}/teams/{team}',
	'GET /repos/{owner}/{repo}/times',
	'GET /repos/{owner}/{repo}/topics',
	'PUT /repos/{owner}/{repo}/topics',
	'PUT /repos/{owner}/{repo}/topics/{topic}',
	'DELETE /repos/{owner}/{repo}/topics/{topic}',
	'POST /repos/{owner}/{repo}/transfer',
	'POST /repos/{owner}/{repo}/transfer/accept',
	'POST /repos/{owner}/{repo}/transfer/reject',
	'POST /repos/{owner}/{repo}/wiki/new',
	'GET /repos/{owner}/{repo}/wiki/page/{pageName}',
	'DELETE /repos/{owner}/{repo}/wiki/page/{pageName}',
	'PATCH /repos/{owner}/{repo}/wiki/page/{pageName}',
	'GET /repos/{owner}/{repo}/wiki/pages',
	'GET /repos/{owner}/{repo}/wiki/revisions/{pageName}',
	'POST /repos/{template_owner}/{template_repo}/generate',
	'GET /repos/issues/search',
	'POST /repos/migrate',
	'GET /repos/search',
	'GET /repositories/{id}',
]);

const repoPaths = Object.keys(swagger.paths).filter(
	(p) => p.split('/')[1] === 'repos' || p.split('/')[1] === 'repositories',
);

const missing = [];
for (const swPath of repoPaths) {
	const methods = Object.keys(swagger.paths[swPath]).filter(
		(k) => !swagger.paths[swPath][k].deprecated,
	);
	for (const method of methods) {
		const key = method.toUpperCase() + ' ' + swPath;
		if (!routingCoverage.has(key)) {
			missing.push(key);
		}
	}
}

if (missing.length === 0) {
	console.log('All /repos/* non-deprecated paths covered! Coverage count=' + routingCoverage.size);
} else {
	console.log('Missing: ' + missing.length);
	missing.sort().forEach((p) => console.log(' ', p));
}

const total = repoPaths.flatMap((p) =>
	Object.keys(swagger.paths[p]).filter((k) => !swagger.paths[p][k].deprecated),
).length;
console.log('Total non-deprecated /repos+/repositories operations in swagger:', total);
