import type { ILoadOptionsFunctions, INodePropertyOptions } from 'n8n-workflow';

const operationsByResource: Record<string, INodePropertyOptions[]> = {
	admin: [
		{
			name: 'Add Quota Rule',
			value: 'addQuotaRule',
			action: 'Add a quota rule to a group',
			description: 'Add a quota rule to a quota group',
		},
		{
			name: 'Add User To Quota Group',
			value: 'addUserToQuotaGroup',
			action: 'Add user to quota group',
			description: 'Add a user to a quota group',
		},
		{
			name: 'Adopt Repository',
			value: 'adoptRepo',
			action: 'Adopt an unadopted repository',
			description: 'Adopt an unadopted git repository',
		},
		{
			name: 'Create Hook',
			value: 'createHook',
			action: 'Create a system webhook',
			description: 'Create a system-level webhook',
		},
		{
			name: 'Create Quota Group',
			value: 'createQuotaGroup',
			action: 'Create a quota group',
			description: 'Create a new quota group',
		},
		{
			name: 'Create Quota Rule',
			value: 'createQuotaRule',
			action: 'Create a quota rule',
			description: 'Create a new quota rule',
		},
		{
			name: 'Create User',
			value: 'createUser',
			action: 'Create a user',
			description: 'Create a new user',
		},
		{
			name: 'Create User Org',
			value: 'createUserOrg',
			action: 'Create an org for a user',
			description: 'Create an organization for a specific user',
		},
		{
			name: 'Create User Public Key',
			value: 'createUserPublicKey',
			action: 'Create a public key for a user',
			description: 'Add a public key for a specific user',
		},
		{
			name: 'Create User Repository',
			value: 'createUserRepo',
			action: 'Create a repository for a user',
			description: 'Create a repository for a specific user',
		},
		{
			name: 'Delete Hook',
			value: 'deleteHook',
			action: 'Delete a system webhook',
			description: 'Delete a system-level webhook',
		},
		{
			name: 'Delete Quota Group',
			value: 'deleteQuotaGroup',
			action: 'Delete a quota group',
			description: 'Delete a quota group',
		},
		{
			name: 'Delete Quota Group Rule',
			value: 'deleteQuotaGroupRule',
			action: 'Delete a rule from quota group',
			description: 'Delete a quota rule from a quota group',
		},
		{
			name: 'Delete Quota Rule',
			value: 'deleteQuotaRule',
			action: 'Delete a quota rule',
			description: 'Delete a quota rule',
		},
		{
			name: 'Delete Unadopted Repository',
			value: 'deleteUnadopted',
			action: 'Delete an unadopted repository',
			description: 'Delete an unadopted git repository',
		},
		{
			name: 'Delete User',
			value: 'deleteUser',
			action: 'Delete a user',
			description: 'Delete a user account',
		},
		{
			name: 'Delete User Email',
			value: 'deleteUserEmail',
			action: 'Delete user email',
			description: 'Delete email addresses from a user',
		},
		{
			name: 'Delete User Public Key',
			value: 'deleteUserPublicKey',
			action: 'Delete a public key from user',
			description: 'Delete a public key from a specific user',
		},
		{
			name: 'Get All Emails',
			value: 'getAllEmails',
			action: 'Get all user emails',
			description: 'List all email addresses in the system',
		},
		{
			name: 'Get Cron Jobs',
			value: 'getCronJobs',
			action: 'Get cron jobs',
			description: 'List all cron tasks',
		},
		{
			name: 'Get Hook',
			value: 'getHook',
			action: 'Get a system webhook',
			description: 'Get a system-level webhook by ID',
		},
		{
			name: 'Get Many Hooks',
			value: 'getManyHooks',
			action: 'Get system webhooks',
			description: 'List system-level webhooks',
		},
		{
			name: 'Get Many Orgs',
			value: 'getManyOrgs',
			action: 'Get organizations',
			description: 'List all organizations',
		},
		{
			name: 'Get Many Unadopted',
			value: 'getManyUnadopted',
			action: 'Get unadopted repositories',
			description: 'List unadopted git repositories',
		},
		{
			name: 'Get Many Users',
			value: 'getManyUsers',
			action: 'Get users',
			description: 'List all users',
		},
		{
			name: 'Get Quota Group',
			value: 'getQuotaGroup',
			action: 'Get a quota group',
			description: 'Get a specific quota group',
		},
		{
			name: 'Get Quota Group Users',
			value: 'getQuotaGroupUsers',
			action: 'Get users in quota group',
			description: 'List users in a quota group',
		},
		{
			name: 'Get Quota Groups',
			value: 'getQuotaGroups',
			action: 'Get quota groups',
			description: 'List all quota groups',
		},
		{
			name: 'Get Quota Rule',
			value: 'getQuotaRule',
			action: 'Get a quota rule',
			description: 'Get a specific quota rule',
		},
		{
			name: 'Get Quota Rules',
			value: 'getQuotaRules',
			action: 'Get quota rules',
			description: 'List all quota rules',
		},
		{
			name: 'Get Runner Jobs',
			value: 'getRunnerJobs',
			action: 'Get runner jobs',
			description: 'Search admin runner jobs',
		},
		{
			name: 'Get Runner Registration Token',
			value: 'getRunnerRegistrationToken',
			action: 'Get runner registration token',
			description: 'Get the registration token for admin runners',
		},
		{
			name: 'Get User Emails',
			value: 'getUserEmails',
			action: 'Get user emails',
			description: 'List email addresses for a specific user',
		},
		{
			name: 'Get User Quota',
			value: 'getUserQuota',
			action: 'Get user quota',
			description: 'Get storage quota summary for a user',
		},
		{
			name: 'Remove User From Quota Group',
			value: 'removeUserFromQuotaGroup',
			action: 'Remove user from quota group',
			description: 'Remove a user from a quota group',
		},
		{
			name: 'Rename User',
			value: 'renameUser',
			action: 'Rename a user',
			description: 'Rename a user account',
		},
		{
			name: 'Run Cron Job',
			value: 'runCronJob',
			action: 'Run a cron job',
			description: 'Run a specific cron task',
		},
		{
			name: 'Search Emails',
			value: 'searchEmails',
			action: 'Search user emails',
			description: 'Search email addresses across users',
		},
		{
			name: 'Set User Quota Group',
			value: 'setUserQuotaGroup',
			action: 'Set user quota group',
			description: 'Set the quota group for a user',
		},
		{
			name: 'Update Hook',
			value: 'updateHook',
			action: 'Update a system webhook',
			description: 'Update a system-level webhook',
		},
		{
			name: 'Update Quota Rule',
			value: 'updateQuotaRule',
			action: 'Update a quota rule',
			description: 'Update an existing quota rule',
		},
		{
			name: 'Update User',
			value: 'updateUser',
			action: 'Update a user',
			description: 'Edit a user account',
		},
	],
	branch: [
		{
			name: 'Create',
			value: 'create',
			action: 'Create a branch',
			description: 'Create a branch in a repository',
		},
		{
			name: 'Delete',
			value: 'delete',
			action: 'Delete a branch',
			description: 'Delete a branch in a repository',
		},
		{
			name: 'Get',
			value: 'get',
			action: 'Get a branch',
			description: 'Get a branch in a repository',
		},
		{
			name: 'Get Many',
			value: 'getAll',
			action: 'Get branches in a repository',
			description: 'List branches in a repository',
		},
		{
			name: 'Update',
			value: 'update',
			action: 'Update a branch',
			description: 'Update a branch in a repository',
		},
	],
	branchProtection: [
		{
			name: 'Create',
			value: 'create',
			action: 'Create a branch protection rule',
			description: 'Create a branch protection rule in a repository',
		},
		{
			name: 'Delete',
			value: 'delete',
			action: 'Delete a branch protection rule',
			description: 'Delete a branch protection rule in a repository',
		},
		{
			name: 'Get',
			value: 'get',
			action: 'Get a branch protection rule',
			description: 'Get a branch protection rule in a repository',
		},
		{
			name: 'Get Many',
			value: 'getAll',
			action: 'Get branch protection rules in a repository',
			description: 'List branch protection rules in a repository',
		},
		{
			name: 'Update',
			value: 'update',
			action: 'Update a branch protection rule',
			description: 'Update a branch protection rule in a repository',
		},
	],
	collaborator: [
		{
			name: 'Add',
			value: 'add',
			action: 'Add a collaborator',
			description: 'Add a collaborator to a repository',
		},
		{
			name: 'Get',
			value: 'get',
			action: 'Get a collaborator',
			description: 'Check if a user is a collaborator',
		},
		{
			name: 'Get Many',
			value: 'getAll',
			action: 'Get collaborators in a repository',
			description: 'List collaborators in a repository',
		},
		{
			name: 'Get Permission',
			value: 'getPermission',
			action: 'Get collaborator permissions',
			description: 'Get repository permissions for a collaborator',
		},
		{
			name: 'Remove',
			value: 'remove',
			action: 'Remove a collaborator',
			description: 'Remove a collaborator from a repository',
		},
	],
	commitStatus: [
		{
			name: 'Create',
			value: 'create',
			action: 'Create a commit status',
			description: 'Create a commit status by SHA',
		},
		{
			name: 'Get Combined By Ref',
			value: 'getCombinedByRef',
			action: 'Get combined commit status by reference',
			description: 'Get combined commit status by branch, tag, or reference',
		},
		{
			name: 'Get Many By Ref',
			value: 'getManyByRef',
			action: 'Get commit statuses by reference',
			description: 'Get commit statuses by branch, tag, or reference',
		},
		{
			name: 'Get Many By SHA',
			value: 'getManyBySha',
			action: 'Get commit statuses by SHA',
			description: 'Get commit statuses by commit SHA',
		},
	],
	repository: [
		{
			name: 'Add Flag',
			value: 'addFlag',
			action: 'Add a repository flag',
			description: 'Add a named flag to a repository',
		},
		{
			name: 'Add Team',
			value: 'addTeam',
			action: 'Add a team to a repository',
			description: 'Assign an existing team to a repository',
		},
		{
			name: 'Add Topic',
			value: 'addTopic',
			action: 'Add a topic to a repository',
			description: 'Add one topic to a repository',
		},
		{
			name: 'Add Push Mirror',
			value: 'addPushMirror',
			action: 'Add a push mirror',
			description: 'Set up a new push mirror for a repository',
		},
		{
			name: 'Apply Diff Patch',
			value: 'applyDiffPatch',
			action: 'Apply a repository diff patch',
			description: 'Apply an update patch to repository content',
		},
		{
			name: 'Create Action Variable',
			value: 'createActionVariable',
			action: 'Create an actions variable',
			description: 'Create a repository-level actions variable',
		},
		{
			name: 'Check Flag',
			value: 'checkFlag',
			action: 'Check repository flag',
			description: 'Check whether a repository has a named flag',
		},
		{
			name: 'Check Team',
			value: 'checkTeam',
			action: 'Check a repository team assignment',
			description: 'Check whether a team is assigned to a repository',
		},
		{
			name: 'Compare',
			value: 'compare',
			action: 'Compare commits or branches',
			description: 'Get comparison information between two refs',
		},
		{
			name: 'Convert',
			value: 'convert',
			action: 'Convert mirror repository',
			description: 'Convert a mirrored repository to a normal repository',
		},
		{
			name: 'Create Tag',
			value: 'createTag',
			action: 'Create a tag',
			description: 'Create a new git tag in a repository',
		},
		{
			name: 'Create Fork',
			value: 'createFork',
			action: 'Fork a repository',
			description: 'Create a fork of a repository',
		},
		{
			name: 'Create Tag Protection',
			value: 'createTagProtection',
			action: 'Create a tag protection rule',
			description: 'Create a protected tag rule in a repository',
		},
		{
			name: 'Delete',
			value: 'delete',
			action: 'Delete a repository',
			description: 'Delete a repository by owner and name',
		},
		{
			name: 'Delete Flag',
			value: 'deleteFlag',
			action: 'Delete repository flag',
			description: 'Remove a named flag from a repository',
		},
		{
			name: 'Delete Flags',
			value: 'deleteFlags',
			action: 'Delete all repository flags',
			description: 'Remove all flags from a repository',
		},
		{
			name: 'Delete Tag',
			value: 'deleteTag',
			action: 'Delete a tag',
			description: 'Delete a tag by name in a repository',
		},
		{
			name: 'Delete Tag Protection',
			value: 'deleteTagProtection',
			action: 'Delete a tag protection rule',
			description: 'Delete a protected tag rule by ID',
		},
		{
			name: 'Delete Topic',
			value: 'deleteTopic',
			action: 'Delete a topic',
			description: 'Delete one topic from a repository',
		},
		{
			name: 'Delete Git Note',
			value: 'deleteGitNote',
			action: 'Delete a git note',
			description: 'Delete a git note for a commit reference',
		},
		{
			name: 'Delete Push Mirror',
			value: 'deletePushMirror',
			action: 'Delete a push mirror',
			description: 'Delete a push mirror by remote name',
		},
		{
			name: 'Delete Avatar',
			value: 'deleteAvatar',
			action: 'Delete repository avatar',
			description: 'Delete a repository avatar image',
		},
		{
			name: 'Delete Action Secret',
			value: 'deleteActionSecret',
			action: 'Delete an actions secret',
			description: 'Delete a repository-level actions secret',
		},
		{
			name: 'Delete Action Variable',
			value: 'deleteActionVariable',
			action: 'Delete an actions variable',
			description: 'Delete a repository-level actions variable',
		},
		{
			name: 'Get Signing Key',
			value: 'getSigningKey',
			action: 'Get repository signing key',
			description: 'Get signing-key.gpg for a repository',
		},
		{
			name: 'Get',
			value: 'get',
			action: 'Get a repository',
			description: 'Get a repository by owner and name',
		},
		{
			name: 'Get Action Runs',
			value: 'getActionRuns',
			action: 'Get actions runs',
			description: 'List actions runs for a repository',
		},
		{
			name: 'Get Action Run',
			value: 'getActionRun',
			action: 'Get an actions run',
			description: 'Get a single actions run by run ID',
		},
		{
			name: 'Get Action Runner Jobs',
			value: 'getActionRunnerJobs',
			action: 'Get actions runner jobs',
			description: 'Search repository actions runner jobs by labels',
		},
		{
			name: 'Get Action Secrets',
			value: 'getActionSecrets',
			action: 'Get actions secrets',
			description: 'List repository-level actions secrets',
		},
		{
			name: 'Get Action Tasks',
			value: 'getActionTasks',
			action: 'Get actions tasks',
			description: 'List repository actions tasks',
		},
		{
			name: 'Get Action Variable',
			value: 'getActionVariable',
			action: 'Get an actions variable',
			description: 'Get a repository-level actions variable by name',
		},
		{
			name: 'Get Action Variables',
			value: 'getActionVariables',
			action: 'Get actions variables',
			description: 'List repository-level actions variables',
		},
		{
			name: 'Get Archive',
			value: 'getArchive',
			action: 'Get a repository archive',
			description: 'Download an archive for a repository reference',
		},
		{
			name: 'Get Assignees',
			value: 'getAssignees',
			action: 'Get assignable users',
			description: 'List users with write access that can be assigned',
		},
		{
			name: 'Get Activity Feeds',
			value: 'getActivityFeeds',
			action: 'Get repository activity feeds',
			description: 'List activity feeds for a repository',
		},
		{
			name: 'Get By ID',
			value: 'getById',
			action: 'Get a repository by ID',
			description: 'Get a repository by its numeric ID',
		},
		{
			name: 'Get EditorConfig',
			value: 'getEditorConfig',
			action: 'Get file EditorConfig',
			description: 'Get resolved EditorConfig rules for a repository file',
		},
		{
			name: 'Get Flags',
			value: 'getFlags',
			action: 'Get repository flags',
			description: 'List all flags assigned to a repository',
		},
		{
			name: 'Get Many',
			value: 'getMany',
			action: 'Get repositories for an owner',
			description: 'Get repositories for an owner',
		},
		{
			name: 'Get Commit Pull Request',
			value: 'getCommitPullRequest',
			action: 'Get pull request for commit',
			description: 'Get the pull request associated with a commit SHA',
		},
		{
			name: 'Get Git Annotated Tag',
			value: 'getGitAnnotatedTag',
			action: 'Get git annotated tag object',
			description: 'Get an annotated tag object by SHA',
		},
		{
			name: 'Get Git Blob',
			value: 'getGitBlob',
			action: 'Get git blob by SHA',
			description: 'Get a git blob object by SHA',
		},
		{
			name: 'Get Git Blobs',
			value: 'getGitBlobs',
			action: 'Get git blobs by SHAs',
			description: 'Get multiple git blobs from comma-separated SHAs',
		},
		{
			name: 'Get Git Commit',
			value: 'getGitCommit',
			action: 'Get git commit by SHA',
			description: 'Get a single commit by git ref or SHA',
		},
		{
			name: 'Get Git Commit Diff Or Patch',
			value: 'getGitCommitDiffOrPatch',
			action: 'Get commit diff or patch',
			description: 'Download a commit as diff or patch text',
		},
		{
			name: 'Get Git Note',
			value: 'getGitNote',
			action: 'Get git note',
			description: 'Get a git note for a commit reference',
		},
		{
			name: 'Get Git Refs',
			value: 'getGitRefs',
			action: 'Get repository git refs',
			description: 'List all git refs in a repository',
		},
		{
			name: 'Get Git Refs By Ref',
			value: 'getGitRefsByRef',
			action: 'Get repository git refs by pattern',
			description: 'List git refs matching a ref pattern',
		},
		{
			name: 'Get Git Tree',
			value: 'getGitTree',
			action: 'Get git tree',
			description: 'Get a git tree by commit SHA',
		},
		{
			name: 'Get Many Commits',
			value: 'getCommits',
			action: 'Get commits in a repository',
			description: 'List commits in a repository',
		},
		{
			name: 'Get Many Forks',
			value: 'getForks',
			action: 'Get repository forks',
			description: 'List forks for a repository',
		},
		{
			name: 'Get Many Reviewers',
			value: 'getReviewers',
			action: 'Get users that can review',
			description: 'List users that can be requested as reviewers',
		},
		{
			name: 'Get Many Stargazers',
			value: 'getStargazers',
			action: 'Get stargazers in a repository',
			description: 'List users who starred a repository',
		},
		{
			name: 'Get Many Subscribers',
			value: 'getSubscribers',
			action: 'Get subscribers in a repository',
			description: 'List users watching a repository',
		},
		{
			name: 'Get Many Tag Protections',
			value: 'getTagProtections',
			action: 'Get tag protection rules',
			description: 'List protected tag rules in a repository',
		},
		{
			name: 'Get Many Tags',
			value: 'getTags',
			action: 'Get tags in a repository',
			description: 'List tags in a repository',
		},
		{
			name: 'Get Many Teams',
			value: 'getTeams',
			action: 'Get teams in a repository',
			description: 'List teams assigned to a repository',
		},
		{
			name: 'Get Many Topics',
			value: 'getTopics',
			action: 'Get topics in a repository',
			description: 'List topics assigned to a repository',
		},
		{
			name: 'Get Sync Fork Branch Info',
			value: 'getSyncForkBranchInfo',
			action: 'Get sync info for a fork branch',
			description: 'Get sync status for a specific fork branch',
		},
		{
			name: 'Get Languages',
			value: 'getLanguages',
			action: 'Get repository languages',
			description: 'Get language statistics for a repository',
		},
		{
			name: 'Get Issue Config',
			value: 'getIssueConfig',
			action: 'Get issue config',
			description: 'Get repository issue configuration',
		},
		{
			name: 'Get Issue Templates',
			value: 'getIssueTemplates',
			action: 'Get issue templates',
			description: 'List available issue templates for a repository',
		},
		{
			name: 'Get Sync Fork Default Info',
			value: 'getSyncForkDefaultInfo',
			action: 'Get sync info for default branch',
			description: 'Get sync status for the default fork branch',
		},
		{
			name: 'Get Subscription',
			value: 'getSubscription',
			action: 'Get current user subscription',
			description: 'Check if current user watches a repository',
		},
		{
			name: 'Get Tag',
			value: 'getTag',
			action: 'Get a tag',
			description: 'Get a tag by name in a repository',
		},
		{
			name: 'Get Tag Protection',
			value: 'getTagProtection',
			action: 'Get a tag protection rule',
			description: 'Get a protected tag rule by ID',
		},
		{
			name: 'Get Tracked Times',
			value: 'getTrackedTimes',
			action: 'Get tracked times in a repository',
			description: 'List tracked issue times in a repository',
		},
		{
			name: 'Get Notifications',
			value: 'getNotifications',
			action: 'Get repository notifications',
			description: 'List notifications for a repository',
		},
		{
			name: 'Get New Pin Allowed',
			value: 'getNewPinAllowed',
			action: 'Get issue pin allowance',
			description: 'Check whether new issue pins are allowed',
		},
		{
			name: 'Get Pinned Issues',
			value: 'getPinnedIssues',
			action: 'Get pinned issues',
			description: 'List pinned issues in a repository',
		},
		{
			name: 'Get Pinned Pull Requests',
			value: 'getPinnedPullRequests',
			action: 'Get pinned pull requests',
			description: 'List pinned pull requests in a repository',
		},
		{
			name: 'Get Pull Request By Base Head',
			value: 'getPullRequestByBaseHead',
			action: 'Get pull request by base/head',
			description: 'Get a pull request by base and head refs',
		},
		{
			name: 'Get Raw File',
			value: 'getRawFile',
			action: 'Get raw file content',
			description: 'Get a raw file from a repository path',
		},
		{
			name: 'Get Push Mirror',
			value: 'getPushMirror',
			action: 'Get a push mirror',
			description: 'Get a push mirror by remote name',
		},
		{
			name: 'Get Push Mirrors',
			value: 'getPushMirrors',
			action: 'Get push mirrors',
			description: 'List push mirrors for a repository',
		},
		{
			name: 'Get Runner Registration Token',
			value: 'getRunnerRegistrationToken',
			action: 'Get actions runner registration token',
			description: 'Get the registration token for repository actions runners',
		},
		{
			name: 'Get Raw File or LFS',
			value: 'getRawFileOrLfs',
			action: 'Get raw file or LFS object',
			description: 'Get raw file bytes or LFS object from repository',
		},
		{
			name: 'Mark Notifications',
			value: 'markNotifications',
			action: 'Mark repository notifications',
			description: 'Mark repository notifications as read, unread, or pinned',
		},
		{
			name: 'Migrate',
			value: 'migrate',
			action: 'Migrate remote repository',
			description: 'Migrate a remote git repository into this instance',
		},
		{
			name: 'Mirror Sync',
			value: 'mirrorSync',
			action: 'Sync mirrored repository',
			description: 'Trigger a mirror sync for a repository',
		},
		{
			name: 'Dispatch Workflow',
			value: 'dispatchWorkflow',
			action: 'Dispatch a workflow',
			description: 'Trigger a workflow dispatch for a repository workflow file',
		},
		{
			name: 'Replace Flags',
			value: 'replaceFlags',
			action: 'Replace repository flags',
			description: 'Replace all flags of a repository',
		},
		{
			name: 'Search',
			value: 'search',
			action: 'Search repositories',
			description: 'Search repositories visible to the authenticated user',
		},
		{
			name: 'Remove Team',
			value: 'removeTeam',
			action: 'Remove a team from a repository',
			description: 'Remove a team assignment from a repository',
		},
		{
			name: 'Replace Topics',
			value: 'replaceTopics',
			action: 'Replace repository topics',
			description: 'Replace all topics for a repository',
		},
		{
			name: 'Set Git Note',
			value: 'setGitNote',
			action: 'Set git note',
			description: 'Set a git note for a commit reference',
		},
		{
			name: 'Sync Fork Branch',
			value: 'syncForkBranch',
			action: 'Sync a fork branch',
			description: 'Sync a specific fork branch with base',
		},
		{
			name: 'Sync Fork Default',
			value: 'syncForkDefault',
			action: 'Sync default fork branch',
			description: 'Sync the default fork branch with base',
		},
		{
			name: 'Sync Push Mirrors',
			value: 'syncPushMirrors',
			action: 'Sync push mirrors',
			description: 'Sync all push mirrors for a repository',
		},
		{
			name: 'Transfer',
			value: 'transfer',
			action: 'Transfer repository ownership',
			description: 'Transfer a repository to another owner',
		},
		{
			name: 'Transfer Accept',
			value: 'transferAccept',
			action: 'Accept a repository transfer',
			description: 'Accept a pending repository transfer',
		},
		{
			name: 'Transfer Reject',
			value: 'transferReject',
			action: 'Reject a repository transfer',
			description: 'Reject a pending repository transfer',
		},
		{
			name: 'Unwatch',
			value: 'unwatch',
			action: 'Unwatch a repository',
			description: 'Unwatch a repository for the current user',
		},
		{
			name: 'Upsert Action Secret',
			value: 'upsertActionSecret',
			action: 'Upsert an actions secret',
			description: 'Create or update a repository-level actions secret',
		},
		{
			name: 'Update Action Variable',
			value: 'updateActionVariable',
			action: 'Update an actions variable',
			description: 'Update a repository-level actions variable',
		},
		{
			name: 'Update',
			value: 'update',
			action: 'Update a repository',
			description: 'Edit repository settings and metadata',
		},
		{
			name: 'Update Tag Protection',
			value: 'updateTagProtection',
			action: 'Update a tag protection rule',
			description: 'Edit a protected tag rule by ID',
		},
		{
			name: 'Update Avatar',
			value: 'updateAvatar',
			action: 'Update repository avatar',
			description: 'Update a repository avatar image',
		},
		{
			name: 'Watch',
			value: 'watch',
			action: 'Watch a repository',
			description: 'Watch a repository for the current user',
		},
		{
			name: 'Validate Issue Config',
			value: 'validateIssueConfig',
			action: 'Validate issue config',
			description: 'Get issue configuration validation details',
		},
	],
	issue: [
		{
			name: 'Add Block',
			value: 'addBlock',
			action: 'Block an issue',
			description: 'Mark another issue as blocked by this issue',
		},
		{
			name: 'Add Dependency',
			value: 'addDependency',
			action: 'Add an issue dependency',
			description: 'Make this issue depend on another issue',
		},
		{
			name: 'Add Subscription',
			value: 'addSubscription',
			action: 'Subscribe a user to an issue',
			description: 'Subscribe a user to this issue',
		},
		{
			name: 'Add Time',
			value: 'addTime',
			action: 'Add tracked time to an issue',
			description: 'Add a tracked time entry to this issue',
		},
		{
			name: 'Add Reaction',
			value: 'addReaction',
			action: 'Add issue reaction',
			description: 'Add a reaction to this issue',
		},
		{
			name: 'Check Subscription',
			value: 'checkSubscription',
			action: 'Check issue subscription',
			description: 'Check whether current user is subscribed to this issue',
		},
		{
			name: 'Create',
			value: 'create',
			action: 'Create an issue',
			description: 'Create a new issue',
		},
		{
			name: 'Create Attachment',
			value: 'createAttachment',
			action: 'Create issue attachment',
			description: 'Upload an attachment to this issue',
		},
		{
			name: 'Delete Block',
			value: 'deleteBlock',
			action: 'Unblock an issue',
			description: 'Remove a blocking relation from this issue',
		},
		{
			name: 'Delete Dependency',
			value: 'deleteDependency',
			action: 'Delete an issue dependency',
			description: 'Remove a dependency from this issue',
		},
		{
			name: 'Delete',
			value: 'delete',
			action: 'Delete an issue',
			description: 'Delete an issue by number',
		},
		{
			name: 'Delete Attachment',
			value: 'deleteAttachment',
			action: 'Delete issue attachment',
			description: 'Delete an attachment from this issue',
		},
		{
			name: 'Delete Stopwatch',
			value: 'deleteStopwatch',
			action: 'Delete issue stopwatch',
			description: 'Delete existing stopwatch for this issue',
		},
		{
			name: 'Delete Reaction',
			value: 'deleteReaction',
			action: 'Delete issue reaction',
			description: 'Remove a reaction from this issue',
		},
		{
			name: 'Delete Subscription',
			value: 'deleteSubscription',
			action: 'Unsubscribe user from issue',
			description: 'Unsubscribe a user from this issue',
		},
		{
			name: 'Delete Time',
			value: 'deleteTime',
			action: 'Delete tracked time from an issue',
			description: 'Delete one tracked time entry by ID',
		},
		{
			name: 'Get Blocks',
			value: 'getBlocks',
			action: 'Get blocked issues',
			description: 'List issues blocked by this issue',
		},
		{
			name: 'Get Attachment',
			value: 'getAttachment',
			action: 'Get issue attachment',
			description: 'Get one attachment from this issue',
		},
		{
			name: 'Get Attachments',
			value: 'getAttachments',
			action: 'Get issue attachments',
			description: 'List attachments on this issue',
		},
		{
			name: 'Get Dependencies',
			value: 'getDependencies',
			action: 'Get issue dependencies',
			description: 'List issues that block this issue',
		},
		{
			name: 'Get',
			value: 'get',
			action: 'Get an issue',
			description: 'Get the data of a single issue',
		},
		{
			name: 'Get Reactions',
			value: 'getReactions',
			action: 'Get issue reactions',
			description: 'List reactions on this issue',
		},
		{
			name: 'Get Subscriptions',
			value: 'getSubscriptions',
			action: 'Get issue subscriptions',
			description: 'List users subscribed to this issue',
		},
		{
			name: 'Get Timeline',
			value: 'getTimeline',
			action: 'Get issue timeline',
			description: 'List timeline events and comments for an issue',
		},
		{
			name: 'Get Times',
			value: 'getTimes',
			action: 'Get issue tracked times',
			description: 'List tracked times for an issue',
		},
		{
			name: 'Get Many',
			value: 'getAll',
			action: 'Get issues in a repository',
			description: 'Get issues in a repository',
		},
		{
			name: 'Search',
			value: 'search',
			action: 'Search issues',
			description: 'Search issues across repositories you can access',
		},
		{
			name: 'Move Pin',
			value: 'movePin',
			action: 'Move pinned issue position',
			description: 'Move a pinned issue to a specific position',
		},
		{
			name: 'Pin',
			value: 'pin',
			action: 'Pin an issue',
			description: 'Pin an issue in the repository',
		},
		{
			name: 'Reset Time',
			value: 'resetTime',
			action: 'Reset issue tracked times',
			description: 'Delete all tracked time entries for this issue',
		},
		{
			name: 'Start Stopwatch',
			value: 'startStopwatch',
			action: 'Start issue stopwatch',
			description: 'Start a stopwatch on this issue',
		},
		{
			name: 'Stop Stopwatch',
			value: 'stopStopwatch',
			action: 'Stop issue stopwatch',
			description: 'Stop the running stopwatch on this issue',
		},
		{
			name: 'Unpin',
			value: 'unpin',
			action: 'Unpin an issue',
			description: 'Unpin an issue in the repository',
		},
		{
			name: 'Update',
			value: 'update',
			action: 'Update an issue',
			description: 'Edit issue fields by number',
		},
		{
			name: 'Update Attachment',
			value: 'updateAttachment',
			action: 'Update issue attachment',
			description: 'Edit metadata for an issue attachment',
		},
		{
			name: 'Update Deadline',
			value: 'updateDeadline',
			action: 'Update issue deadline',
			description: 'Set or update the issue deadline',
		},
	],
	issueComment: [
		{
			name: 'Add Reaction',
			value: 'addReaction',
			action: 'Add issue comment reaction',
			description: 'Add a reaction to an issue comment',
		},
		{
			name: 'Create',
			value: 'create',
			action: 'Create an issue comment',
			description: 'Create a comment on an issue',
		},
		{
			name: 'Create Attachment',
			value: 'createAttachment',
			action: 'Create issue comment attachment',
			description: 'Upload an attachment to an issue comment',
		},
		{
			name: 'Delete Attachment',
			value: 'deleteAttachment',
			action: 'Delete issue comment attachment',
			description: 'Delete an attachment from an issue comment',
		},
		{
			name: 'Delete Reaction',
			value: 'deleteReaction',
			action: 'Delete issue comment reaction',
			description: 'Remove a reaction from an issue comment',
		},
		{
			name: 'Delete',
			value: 'delete',
			action: 'Delete an issue comment',
			description: 'Delete an issue comment by ID',
		},
		{
			name: 'Get',
			value: 'get',
			action: 'Get an issue comment',
			description: 'Get an issue comment by ID',
		},
		{
			name: 'Get Attachment',
			value: 'getAttachment',
			action: 'Get issue comment attachment',
			description: 'Get one attachment from an issue comment',
		},
		{
			name: 'Get Attachments',
			value: 'getAttachments',
			action: 'Get issue comment attachments',
			description: 'List attachments on an issue comment',
		},
		{
			name: 'Get Many',
			value: 'getAll',
			action: 'Get many comments on an issue',
			description: 'Get many comments on an issue',
		},
		{
			name: 'Get Repository Comments',
			value: 'getRepositoryComments',
			action: 'Get comments in a repository',
			description: 'List issue comments across a repository',
		},
		{
			name: 'Get Reactions',
			value: 'getReactions',
			action: 'Get issue comment reactions',
			description: 'List reactions on an issue comment',
		},
		{
			name: 'Update',
			value: 'update',
			action: 'Update an issue comment',
			description: 'Edit an issue comment by ID',
		},
		{
			name: 'Update Attachment',
			value: 'updateAttachment',
			action: 'Update issue comment attachment',
			description: 'Edit metadata for an issue comment attachment',
		},
	],
	issueLabel: [
		{
			name: 'Add',
			value: 'add',
			action: 'Add labels to an issue',
			description: 'Add labels to an issue',
		},
		{
			name: 'Get Many',
			value: 'getAll',
			action: 'Get labels on an issue',
			description: 'Get labels on an issue',
		},
		{
			name: 'Remove',
			value: 'remove',
			action: 'Remove one label from an issue',
			description: 'Remove one label from an issue',
		},
		{
			name: 'Remove All',
			value: 'removeAll',
			action: 'Remove all labels from an issue',
			description: 'Remove all labels from an issue',
		},
		{
			name: 'Replace',
			value: 'replace',
			action: 'Replace labels on an issue',
			description: 'Replace labels on an issue',
		},
	],
	label: [
		{
			name: 'Create',
			value: 'create',
			action: 'Create a label',
			description: 'Create a label in a repository',
		},
		{
			name: 'Delete',
			value: 'delete',
			action: 'Delete a label',
			description: 'Delete a label in a repository',
		},
		{
			name: 'Get',
			value: 'get',
			action: 'Get a label',
			description: 'Get a single label in a repository',
		},
		{
			name: 'Get Many',
			value: 'getAll',
			action: 'Get labels in a repository',
			description: 'Get labels in a repository',
		},
		{
			name: 'Update',
			value: 'update',
			action: 'Update a label',
			description: 'Update a label in a repository',
		},
	],
	milestone: [
		{
			name: 'Create',
			value: 'create',
			action: 'Create a milestone',
			description: 'Create a milestone in a repository',
		},
		{
			name: 'Delete',
			value: 'delete',
			action: 'Delete a milestone',
			description: 'Delete a milestone in a repository',
		},
		{
			name: 'Get',
			value: 'get',
			action: 'Get a milestone',
			description: 'Get a single milestone in a repository',
		},
		{
			name: 'Get Many',
			value: 'getAll',
			action: 'Get milestones in a repository',
			description: 'Get milestones in a repository',
		},
		{
			name: 'Update',
			value: 'update',
			action: 'Update a milestone',
			description: 'Update a milestone in a repository',
		},
	],
	organization: [
		{
			name: 'Block User',
			value: 'blockUser',
			action: 'Block a user',
			description: 'Block a user from an organization',
		},
		{
			name: 'Create',
			value: 'create',
			action: 'Create an organization',
			description: 'Create a new organization',
		},
		{
			name: 'Create Action Variable',
			value: 'createActionVariable',
			action: 'Create an actions variable',
			description: 'Create an actions variable for an organization',
		},
		{
			name: 'Create Hook',
			value: 'createHook',
			action: 'Create a webhook',
			description: 'Create a webhook for an organization',
		},
		{
			name: 'Create Label',
			value: 'createLabel',
			action: 'Create a label',
			description: 'Create a label for an organization',
		},
		{
			name: 'Create Repository',
			value: 'createRepo',
			action: 'Create a repository',
			description: 'Create a repository for an organization',
		},
		{
			name: 'Create Team',
			value: 'createTeam',
			action: 'Create a team',
			description: 'Create a team in an organization',
		},
		{
			name: 'Delete',
			value: 'delete',
			action: 'Delete an organization',
			description: 'Delete an organization',
		},
		{
			name: 'Delete Action Secret',
			value: 'deleteActionSecret',
			action: 'Delete an actions secret',
			description: 'Delete an actions secret for an organization',
		},
		{
			name: 'Delete Action Variable',
			value: 'deleteActionVariable',
			action: 'Delete an actions variable',
			description: 'Delete an actions variable for an organization',
		},
		{
			name: 'Delete Avatar',
			value: 'deleteAvatar',
			action: 'Delete avatar',
			description: 'Delete the avatar of an organization',
		},
		{
			name: 'Delete Hook',
			value: 'deleteHook',
			action: 'Delete a webhook',
			description: 'Delete a webhook for an organization',
		},
		{
			name: 'Delete Label',
			value: 'deleteLabel',
			action: 'Delete a label',
			description: 'Delete a label for an organization',
		},
		{
			name: 'Delete Member',
			value: 'deleteMember',
			action: 'Delete a member',
			description: 'Remove a member from an organization',
		},
		{
			name: 'Delete Public Member',
			value: 'deletePublicMember',
			action: 'Delete public member',
			description: 'Conceal a user as a member of an organization',
		},
		{
			name: 'Get',
			value: 'get',
			action: 'Get an organization',
			description: 'Get an organization by name',
		},
		{
			name: 'Get Action Secrets',
			value: 'getActionSecrets',
			action: 'Get actions secrets',
			description: 'List actions secrets for an organization',
		},
		{
			name: 'Get Action Variable',
			value: 'getActionVariable',
			action: 'Get an actions variable',
			description: 'Get an actions variable for an organization',
		},
		{
			name: 'Get Action Variables',
			value: 'getActionVariables',
			action: 'Get actions variables',
			description: 'List actions variables for an organization',
		},
		{
			name: 'Get Activity Feeds',
			value: 'getActivityFeeds',
			action: 'Get activity feeds',
			description: 'List activity feeds for an organization',
		},
		{
			name: 'Get Many',
			value: 'getAll',
			action: 'Get all organizations',
			description: 'List all organizations',
		},
		{
			name: 'Get Hook',
			value: 'getHook',
			action: 'Get a webhook',
			description: 'Get a webhook for an organization',
		},
		{
			name: 'Get Label',
			value: 'getLabel',
			action: 'Get a label',
			description: 'Get a label for an organization',
		},
		{
			name: 'Get Many Hooks',
			value: 'getManyHooks',
			action: 'Get webhooks',
			description: 'List webhooks for an organization',
		},
		{
			name: 'Get Many Labels',
			value: 'getManyLabels',
			action: 'Get labels',
			description: 'List labels for an organization',
		},
		{
			name: 'Get Many Members',
			value: 'getManyMembers',
			action: 'Get members',
			description: 'List members of an organization',
		},
		{
			name: 'Get Many Public Members',
			value: 'getManyPublicMembers',
			action: 'Get public members',
			description: 'List public members of an organization',
		},
		{
			name: 'Get Many Repos',
			value: 'getManyRepos',
			action: 'Get repositories',
			description: 'List repositories of an organization',
		},
		{
			name: 'Get Many Teams',
			value: 'getManyTeams',
			action: 'Get teams',
			description: 'List teams in an organization',
		},
		{
			name: 'Get Member',
			value: 'getMember',
			action: 'Check membership',
			description: 'Check if a user is a member of an organization',
		},
		{
			name: 'Get Public Member',
			value: 'getPublicMember',
			action: 'Check public membership',
			description: 'Check if a user is a public member of an organization',
		},
		{
			name: 'Get Quota',
			value: 'getQuota',
			action: 'Get quota',
			description: 'Get quota for an organization',
		},
		{
			name: 'Get Quota Artifacts',
			value: 'getQuotaArtifacts',
			action: 'Get quota artifacts',
			description: 'List artifacts counting towards org storage quota',
		},
		{
			name: 'Get Quota Attachments',
			value: 'getQuotaAttachments',
			action: 'Get quota attachments',
			description: 'List attachments counting towards org storage quota',
		},
		{
			name: 'Get Quota Check',
			value: 'getQuotaCheck',
			action: 'Check quota',
			description: 'Check quota for an organization',
		},
		{
			name: 'Get Quota Packages',
			value: 'getQuotaPackages',
			action: 'Get quota packages',
			description: 'List packages counting towards org storage quota',
		},
		{
			name: 'Get Runner Jobs',
			value: 'getRunnerJobs',
			action: 'Get runner jobs',
			description: 'Search runner jobs for an organization',
		},
		{
			name: 'Get Runner Registration Token',
			value: 'getRunnerRegistrationToken',
			action: 'Get runner registration token',
			description: 'Get the registration token for organization runners',
		},
		{
			name: 'List Blocked Users',
			value: 'listBlockedUsers',
			action: 'List blocked users',
			description: 'List users blocked by an organization',
		},
		{
			name: 'Rename',
			value: 'rename',
			action: 'Rename an organization',
			description: 'Rename an organization',
		},
		{
			name: 'Search Teams',
			value: 'searchTeams',
			action: 'Search teams',
			description: 'Search for teams in an organization',
		},
		{
			name: 'Set Public Member',
			value: 'setPublicMember',
			action: 'Set public member',
			description: 'Publicize a user as a member of an organization',
		},
		{
			name: 'Unblock User',
			value: 'unblockUser',
			action: 'Unblock a user',
			description: 'Unblock a user from an organization',
		},
		{
			name: 'Update',
			value: 'update',
			action: 'Update an organization',
			description: 'Edit organization settings',
		},
		{
			name: 'Update Action Variable',
			value: 'updateActionVariable',
			action: 'Update an actions variable',
			description: 'Update an actions variable for an organization',
		},
		{
			name: 'Update Avatar',
			value: 'updateAvatar',
			action: 'Update avatar',
			description: 'Update the avatar of an organization',
		},
		{
			name: 'Update Hook',
			value: 'updateHook',
			action: 'Update a webhook',
			description: 'Update a webhook for an organization',
		},
		{
			name: 'Update Label',
			value: 'updateLabel',
			action: 'Update a label',
			description: 'Update a label for an organization',
		},
		{
			name: 'Upsert Action Secret',
			value: 'upsertActionSecret',
			action: 'Upsert an actions secret',
			description: 'Create or update an actions secret for an organization',
		},
	],
	release: [
		{
			name: 'Create',
			value: 'create',
			action: 'Create a release',
			description: 'Create a release in a repository',
		},
		{
			name: 'Delete',
			value: 'delete',
			action: 'Delete a release',
			description: 'Delete a release by ID',
		},
		{
			name: 'Delete By Tag',
			value: 'deleteByTag',
			action: 'Delete a release by tag',
			description: 'Delete a release by tag name',
		},
		{
			name: 'Get',
			value: 'get',
			action: 'Get a release',
			description: 'Get a release by ID',
		},
		{
			name: 'Get By Tag',
			value: 'getByTag',
			action: 'Get a release by tag',
			description: 'Get a release by tag name',
		},
		{
			name: 'Get Latest',
			value: 'getLatest',
			action: 'Get latest stable release',
			description: 'Get latest non-draft, non-pre-release',
		},
		{
			name: 'Get Many',
			value: 'getAll',
			action: 'Get releases in a repository',
			description: 'Get releases in a repository',
		},
		{
			name: 'Update',
			value: 'update',
			action: 'Update a release',
			description: 'Update a release by ID',
		},
	],
	releaseAttachment: [
		{
			name: 'Create',
			value: 'create',
			action: 'Create a release attachment',
			description: 'Upload or attach an asset to a release',
		},
		{
			name: 'Delete',
			value: 'delete',
			action: 'Delete a release attachment',
			description: 'Delete a release attachment by ID',
		},
		{
			name: 'Get',
			value: 'get',
			action: 'Get a release attachment',
			description: 'Get a release attachment by ID',
		},
		{
			name: 'Get Many',
			value: 'getAll',
			action: 'Get release attachments',
			description: 'List attachments for a release',
		},
		{
			name: 'Update',
			value: 'update',
			action: 'Update a release attachment',
			description: 'Edit metadata for a release attachment',
		},
	],
	pullRequest: [
		{
			name: 'Cancel Auto Merge',
			value: 'cancelAutoMerge',
			action: 'Cancel scheduled auto merge',
			description: 'Cancel the scheduled auto merge for a pull request',
		},
		{
			name: 'Create Review Comment',
			value: 'createReviewComment',
			action: 'Create a review comment',
			description: 'Add a review comment to a pull request review',
		},
		{
			name: 'Create Review Requests',
			value: 'createReviewRequests',
			action: 'Create pull review requests',
			description: 'Request reviewers for a pull request',
		},
		{
			name: 'Create Review',
			value: 'createReview',
			action: 'Create a pull request review',
			description: 'Create a review for a pull request',
		},
		{
			name: 'Create',
			value: 'create',
			action: 'Create a pull request',
			description: 'Create a new pull request',
		},
		{
			name: 'Delete Review Comment',
			value: 'deleteReviewComment',
			action: 'Delete a review comment',
			description: 'Delete a review comment from a pull request review',
		},
		{
			name: 'Delete Review',
			value: 'deleteReview',
			action: 'Delete a pull request review',
			description: 'Delete a specific review from a pull request',
		},
		{
			name: 'Delete Review Requests',
			value: 'deleteReviewRequests',
			action: 'Delete pull review requests',
			description: 'Cancel review requests for a pull request',
		},
		{
			name: 'Dismiss Review',
			value: 'dismissReview',
			action: 'Dismiss a review',
			description: 'Dismiss a pull request review',
		},
		{
			name: 'Get',
			value: 'get',
			action: 'Get a pull request',
			description: 'Retrieve a single pull request by number',
		},
		{
			name: 'Get Commits',
			value: 'getCommits',
			action: 'Get pull request commits',
			description: 'List commits in a pull request',
		},
		{
			name: 'Get Files',
			value: 'getFiles',
			action: 'Get pull request changed files',
			description: 'List changed files in a pull request',
		},
		{
			name: 'Get Diff Or Patch',
			value: 'getDiffOrPatch',
			action: 'Get pull request diff or patch',
			description: 'Download a pull request as diff or patch text',
		},
		{
			name: 'Get Many',
			value: 'getAll',
			action: 'List pull requests',
			description: 'List pull requests for a repository',
		},
		{
			name: 'Get Review',
			value: 'getReview',
			action: 'Get a pull request review',
			description: 'Get a specific review by ID for a pull request',
		},
		{
			name: 'Get Review Comment',
			value: 'getReviewComment',
			action: 'Get a review comment',
			description: 'Get a specific review comment from a pull request review',
		},
		{
			name: 'Get Reviews',
			value: 'getReviews',
			action: 'Get pull request reviews',
			description: 'List reviews for a pull request',
		},
		{
			name: 'Get Review Comments',
			value: 'getReviewComments',
			action: 'Get review comments',
			description: 'List comments for a pull request review',
		},
		{
			name: 'Is Merged',
			value: 'isMerged',
			action: 'Check pull request merged status',
			description: 'Check whether a pull request has been merged',
		},
		{
			name: 'Merge',
			value: 'merge',
			action: 'Merge a pull request',
			description: 'Merge a pull request with a selectable strategy',
		},
		{
			name: 'Submit Review',
			value: 'submitReview',
			action: 'Submit a pull request review',
			description: 'Submit a pending review for a pull request',
		},
		{
			name: 'Undismiss Review',
			value: 'undismissReview',
			action: 'Undismiss a review',
			description: 'Cancel dismissal of a pull request review',
		},
		{
			name: 'Update',
			value: 'update',
			action: 'Update a pull request',
			description: 'Modify fields on an existing pull request',
		},
		{
			name: 'Update Branch',
			value: 'updateBranch',
			action: 'Update pull request branch',
			description: 'Merge or rebase base branch into pull request head',
		},
	],
	repositoryContent: [
		{
			name: 'Change Many',
			value: 'changeMany',
			action: 'Change multiple files',
			description: 'Modify multiple files in a repository',
		},
		{
			name: 'Create',
			value: 'create',
			action: 'Create a file',
			description: 'Create a file in a repository',
		},
		{
			name: 'Delete',
			value: 'delete',
			action: 'Delete a file',
			description: 'Delete a file in a repository',
		},
		{
			name: 'Get',
			value: 'get',
			action: 'Get file or directory contents',
			description: 'Get metadata and contents for a path',
		},
		{
			name: 'Get Root',
			value: 'getRoot',
			action: 'Get root directory contents',
			description: 'Get metadata of root directory entries',
		},
		{
			name: 'Update',
			value: 'update',
			action: 'Update a file',
			description: 'Update a file in a repository',
		},
	],
	repositoryKey: [
		{
			name: 'Create',
			value: 'create',
			action: 'Create a repository key',
			description: 'Add a deploy key to a repository',
		},
		{
			name: 'Delete',
			value: 'delete',
			action: 'Delete a repository key',
			description: 'Delete a deploy key from a repository',
		},
		{
			name: 'Get',
			value: 'get',
			action: 'Get a repository key',
			description: 'Get a deploy key by ID',
		},
		{
			name: 'Get Many',
			value: 'getAll',
			action: 'Get repository keys',
			description: 'List deploy keys in a repository',
		},
	],
	repositoryTemplate: [
		{
			name: 'Generate',
			value: 'generate',
			action: 'Generate a repository from template',
			description: 'Create a repository using a template repository',
		},
	],
	team: [
		{
			name: 'Add Member',
			value: 'addMember',
			action: 'Add a member to a team',
			description: 'Add a user to a team',
		},
		{
			name: 'Add Repository',
			value: 'addRepo',
			action: 'Add a repository to a team',
			description: 'Add a repository to a team',
		},
		{
			name: 'Delete',
			value: 'delete',
			action: 'Delete a team',
			description: 'Delete a team',
		},
		{
			name: 'Get',
			value: 'get',
			action: 'Get a team',
			description: 'Get a team by ID',
		},
		{
			name: 'Get Activity Feeds',
			value: 'getActivityFeeds',
			action: 'Get activity feeds',
			description: 'List activity feeds for a team',
		},
		{
			name: 'Get Many Members',
			value: 'getManyMembers',
			action: 'Get members',
			description: 'List members of a team',
		},
		{
			name: 'Get Many Repos',
			value: 'getManyRepos',
			action: 'Get repositories',
			description: 'List repositories of a team',
		},
		{
			name: 'Get Member',
			value: 'getMember',
			action: 'Check team membership',
			description: 'Check if a user is a member of a team',
		},
		{
			name: 'Get Repository',
			value: 'getRepo',
			action: 'Check team repository',
			description: 'Check if a repository is in a team',
		},
		{
			name: 'Remove Member',
			value: 'removeMember',
			action: 'Remove a member from a team',
			description: 'Remove a user from a team',
		},
		{
			name: 'Remove Repository',
			value: 'removeRepo',
			action: 'Remove a repository from a team',
			description: 'Remove a repository from a team',
		},
		{
			name: 'Update',
			value: 'update',
			action: 'Update a team',
			description: 'Edit a team',
		},
	],
	user: [
		{
			name: 'Add Email',
			value: 'addEmail',
			action: 'Add emails',
			description: 'Add email addresses to the authenticated user',
		},
		{
			name: 'Block User',
			value: 'blockUser',
			action: 'Block a user',
			description: 'Block a user',
		},
		{
			name: 'Check Following',
			value: 'checkFollowing',
			action: 'Check if following user',
			description: 'Check whether the authenticated user follows a user',
		},
		{
			name: 'Check Starring',
			value: 'checkStarring',
			action: 'Check starring a repository',
			description: 'Check whether the authenticated user stars a repository',
		},
		{
			name: 'Create Action Variable',
			value: 'createActionVariable',
			action: 'Create an actions variable',
			description: 'Create an actions variable for the authenticated user',
		},
		{
			name: 'Create GPG Key',
			value: 'createGPGKey',
			action: 'Create a GPG key',
			description: 'Create a GPG key for the authenticated user',
		},
		{
			name: 'Create Hook',
			value: 'createHook',
			action: 'Create a webhook',
			description: 'Create a webhook for the authenticated user',
		},
		{
			name: 'Create OAuth2 Application',
			value: 'createOAuth2Application',
			action: 'Create an OAuth2 application',
			description: 'Create an OAuth2 application for the authenticated user',
		},
		{
			name: 'Create Repository',
			value: 'createRepo',
			action: 'Create a repository',
			description: 'Create a repository for the authenticated user',
		},
		{
			name: 'Create SSH Key',
			value: 'createSSHKey',
			action: 'Create an SSH key',
			description: 'Create an SSH key for the authenticated user',
		},
		{
			name: 'Delete Action Secret',
			value: 'deleteActionSecret',
			action: 'Delete an actions secret',
			description: 'Delete an actions secret for the authenticated user',
		},
		{
			name: 'Delete Action Variable',
			value: 'deleteActionVariable',
			action: 'Delete an actions variable',
			description: 'Delete an actions variable for the authenticated user',
		},
		{
			name: 'Delete Avatar',
			value: 'deleteAvatar',
			action: 'Delete avatar',
			description: 'Delete the avatar of the authenticated user',
		},
		{
			name: 'Delete Email',
			value: 'deleteEmail',
			action: 'Delete emails',
			description: 'Delete email addresses from the authenticated user',
		},
		{
			name: 'Delete GPG Key',
			value: 'deleteGPGKey',
			action: 'Delete a GPG key',
			description: 'Delete a GPG key from the authenticated user',
		},
		{
			name: 'Delete Hook',
			value: 'deleteHook',
			action: 'Delete a webhook',
			description: 'Delete a webhook for the authenticated user',
		},
		{
			name: 'Delete OAuth2 Application',
			value: 'deleteOAuth2Application',
			action: 'Delete an OAuth2 application',
			description: 'Delete an OAuth2 application for the authenticated user',
		},
		{
			name: 'Delete SSH Key',
			value: 'deleteSSHKey',
			action: 'Delete an SSH key',
			description: 'Delete an SSH key from the authenticated user',
		},
		{
			name: 'Follow',
			value: 'follow',
			action: 'Follow a user',
			description: 'Follow a user',
		},
		{
			name: 'Get Action Variable',
			value: 'getActionVariable',
			action: 'Get an actions variable',
			description: 'Get an actions variable for the authenticated user',
		},
		{
			name: 'Get Action Variables',
			value: 'getActionVariables',
			action: 'Get actions variables',
			description: 'List actions variables for the authenticated user',
		},
		{
			name: 'Get Authenticated',
			value: 'getAuthenticated',
			action: 'Get the authenticated user',
			description: 'Get the authenticated user',
		},
		{
			name: 'Get GPG Key',
			value: 'getGPGKey',
			action: 'Get a GPG key',
			description: 'Get a GPG key of the authenticated user',
		},
		{
			name: 'Get GPG Key Token',
			value: 'getGPGKeyToken',
			action: 'Get GPG key token',
			description: 'Get the GPG key token for the authenticated user',
		},
		{
			name: 'Get Hook',
			value: 'getHook',
			action: 'Get a webhook',
			description: 'Get a webhook for the authenticated user',
		},
		{
			name: 'Get Many Emails',
			value: 'getManyEmails',
			action: 'Get emails',
			description: 'List email addresses of the authenticated user',
		},
		{
			name: 'Get Many Followers',
			value: 'getManyFollowers',
			action: 'Get followers',
			description: 'List followers of the authenticated user',
		},
		{
			name: 'Get Many Following',
			value: 'getManyFollowing',
			action: 'Get following',
			description: 'List users followed by the authenticated user',
		},
		{
			name: 'Get Many GPG Keys',
			value: 'getManyGPGKeys',
			action: 'Get GPG keys',
			description: 'List GPG keys of the authenticated user',
		},
		{
			name: 'Get Many Hooks',
			value: 'getManyHooks',
			action: 'Get webhooks',
			description: 'List webhooks of the authenticated user',
		},
		{
			name: 'Get Many Orgs',
			value: 'getManyOrgs',
			action: 'Get organizations',
			description: 'List organizations the authenticated user is a member of',
		},
		{
			name: 'Get Many Repos',
			value: 'getManyRepos',
			action: 'Get repositories',
			description: 'List repositories of the authenticated user',
		},
		{
			name: 'Get Many SSH Keys',
			value: 'getManySSHKeys',
			action: 'Get SSH keys',
			description: 'List SSH keys of the authenticated user',
		},
		{
			name: 'Get Many Starred',
			value: 'getManyStarred',
			action: 'Get starred repos',
			description: 'List repositories starred by the authenticated user',
		},
		{
			name: 'Get Many Stopwatches',
			value: 'getManyStopwatches',
			action: 'Get stopwatches',
			description: 'List running stopwatches for the authenticated user',
		},
		{
			name: 'Get Many Subscriptions',
			value: 'getManySubscriptions',
			action: 'Get subscriptions',
			description: 'List repositories watched by the authenticated user',
		},
		{
			name: 'Get Many Teams',
			value: 'getManyTeams',
			action: 'Get teams',
			description: 'List teams the authenticated user belongs to',
		},
		{
			name: 'Get Many Tracked Times',
			value: 'getManyTrackedTimes',
			action: 'Get tracked times',
			description: 'List tracked issue times for the authenticated user',
		},
		{
			name: 'Get OAuth2 Application',
			value: 'getOAuth2Application',
			action: 'Get an OAuth2 application',
			description: 'Get an OAuth2 application of the authenticated user',
		},
		{
			name: 'Get OAuth2 Applications',
			value: 'getOAuth2Applications',
			action: 'Get OAuth2 applications',
			description: 'List OAuth2 applications of the authenticated user',
		},
		{
			name: 'Get Quota',
			value: 'getQuota',
			action: 'Get quota',
			description: 'Get quota for the authenticated user',
		},
		{
			name: 'Get Quota Artifacts',
			value: 'getQuotaArtifacts',
			action: 'Get quota artifacts',
			description: 'List artifacts counting towards storage quota',
		},
		{
			name: 'Get Quota Attachments',
			value: 'getQuotaAttachments',
			action: 'Get quota attachments',
			description: 'List attachments counting towards storage quota',
		},
		{
			name: 'Get Quota Check',
			value: 'getQuotaCheck',
			action: 'Check quota',
			description: 'Check quota for the authenticated user',
		},
		{
			name: 'Get Quota Packages',
			value: 'getQuotaPackages',
			action: 'Get quota packages',
			description: 'List packages counting towards storage quota',
		},
		{
			name: 'Get Runner Jobs',
			value: 'getRunnerJobs',
			action: 'Get runner jobs',
			description: 'Search runner jobs for the authenticated user',
		},
		{
			name: 'Get Runner Registration Token',
			value: 'getRunnerRegistrationToken',
			action: 'Get runner registration token',
			description: 'Get the registration token for user runners',
		},
		{
			name: 'Get Settings',
			value: 'getSettings',
			action: 'Get settings',
			description: 'Get settings for the authenticated user',
		},
		{
			name: 'Get SSH Key',
			value: 'getSSHKey',
			action: 'Get an SSH key',
			description: 'Get an SSH key of the authenticated user',
		},
		{
			name: 'List Blocked Users',
			value: 'listBlockedUsers',
			action: 'List blocked users',
			description: 'List users blocked by the authenticated user',
		},
		{
			name: 'Star Repo',
			value: 'starRepo',
			action: 'Star a repository',
			description: 'Star a repository',
		},
		{
			name: 'Unblock User',
			value: 'unblockUser',
			action: 'Unblock a user',
			description: 'Unblock a user',
		},
		{
			name: 'Unfollow',
			value: 'unfollow',
			action: 'Unfollow a user',
			description: 'Unfollow a user',
		},
		{
			name: 'Unstar Repo',
			value: 'unstarRepo',
			action: 'Unstar a repository',
			description: 'Unstar a repository',
		},
		{
			name: 'Update Action Variable',
			value: 'updateActionVariable',
			action: 'Update an actions variable',
			description: 'Update an actions variable for the authenticated user',
		},
		{
			name: 'Update Avatar',
			value: 'updateAvatar',
			action: 'Update avatar',
			description: 'Update the avatar of the authenticated user',
		},
		{
			name: 'Update Hook',
			value: 'updateHook',
			action: 'Update a webhook',
			description: 'Update a webhook for the authenticated user',
		},
		{
			name: 'Update OAuth2 Application',
			value: 'updateOAuth2Application',
			action: 'Update an OAuth2 application',
			description: 'Update an OAuth2 application of the authenticated user',
		},
		{
			name: 'Update Settings',
			value: 'updateSettings',
			action: 'Update settings',
			description: 'Update settings for the authenticated user',
		},
		{
			name: 'Upsert Action Secret',
			value: 'upsertActionSecret',
			action: 'Upsert an actions secret',
			description: 'Create or update an actions secret for the authenticated user',
		},
		{
			name: 'Verify GPG Key',
			value: 'verifyGPGKey',
			action: 'Verify GPG key',
			description: 'Verify a GPG key for the authenticated user',
		},
	],
	users: [
		{
			name: 'Check Following',
			value: 'checkFollowing',
			action: 'Check if user follows another',
			description: 'Check whether a user follows another user',
		},
		{
			name: 'Create Token',
			value: 'createToken',
			action: 'Create an access token',
			description: 'Create an access token for a user',
		},
		{
			name: 'Delete Token',
			value: 'deleteToken',
			action: 'Delete an access token',
			description: 'Delete an access token for a user',
		},
		{
			name: 'Get',
			value: 'get',
			action: 'Get a user',
			description: 'Get a user by username',
		},
		{
			name: 'Get Activity Feeds',
			value: 'getActivityFeeds',
			action: 'Get activity feeds',
			description: 'List activity feeds for a user',
		},
		{
			name: 'Get Heatmap',
			value: 'getHeatmap',
			action: 'Get heatmap',
			description: 'Get the heatmap for a user',
		},
		{
			name: 'Get Many Followers',
			value: 'getManyFollowers',
			action: 'Get followers',
			description: 'List followers of a user',
		},
		{
			name: 'Get Many Following',
			value: 'getManyFollowing',
			action: 'Get following',
			description: 'List users followed by a user',
		},
		{
			name: 'Get Many GPG Keys',
			value: 'getManyGPGKeys',
			action: 'Get GPG keys',
			description: 'List GPG keys of a user',
		},
		{
			name: 'Get Many Orgs',
			value: 'getManyOrgs',
			action: 'Get organizations',
			description: 'List organizations a user is a member of',
		},
		{
			name: 'Get Many Repos',
			value: 'getManyRepos',
			action: 'Get repositories',
			description: 'List repositories of a user',
		},
		{
			name: 'Get Many SSH Keys',
			value: 'getManySSHKeys',
			action: 'Get SSH keys',
			description: 'List SSH keys of a user',
		},
		{
			name: 'Get Many Starred',
			value: 'getManyStarred',
			action: 'Get starred repos',
			description: 'List repositories starred by a user',
		},
		{
			name: 'Get Many Subscriptions',
			value: 'getManySubscriptions',
			action: 'Get subscriptions',
			description: 'List repositories watched by a user',
		},
		{
			name: 'Get Org Permissions',
			value: 'getOrgPermissions',
			action: 'Get org permissions',
			description: 'Get user permissions in an organization',
		},
		{
			name: 'Get Tokens',
			value: 'getTokens',
			action: 'Get access tokens',
			description: 'List access tokens for a user',
		},
		{
			name: 'Search',
			value: 'search',
			action: 'Search users',
			description: 'Search for users',
		},
	],
	wikiPage: [
		{
			name: 'Create',
			value: 'create',
			action: 'Create a wiki page',
			description: 'Create a wiki page in a repository',
		},
		{
			name: 'Delete',
			value: 'delete',
			action: 'Delete a wiki page',
			description: 'Delete a wiki page in a repository',
		},
		{
			name: 'Get',
			value: 'get',
			action: 'Get a wiki page',
			description: 'Get a wiki page in a repository',
		},
		{
			name: 'Get Many',
			value: 'getAll',
			action: 'Get wiki pages in a repository',
			description: 'List wiki pages in a repository',
		},
		{
			name: 'Get Revisions',
			value: 'getRevisions',
			action: 'Get wiki page revisions',
			description: 'Get revision history for a wiki page',
		},
		{
			name: 'Update',
			value: 'update',
			action: 'Update a wiki page',
			description: 'Edit a wiki page in a repository',
		},
	],
	webhook: [
		{
			name: 'Create',
			value: 'create',
			action: 'Create a webhook',
			description: 'Create a webhook in a repository',
		},
		{
			name: 'Delete Git Hook',
			value: 'deleteGitHook',
			action: 'Delete a git hook',
			description: 'Delete a git hook in a repository',
		},
		{
			name: 'Delete',
			value: 'delete',
			action: 'Delete a webhook',
			description: 'Delete a webhook in a repository',
		},
		{
			name: 'Get Git Hook',
			value: 'getGitHook',
			action: 'Get a git hook',
			description: 'Get a git hook by ID in a repository',
		},
		{
			name: 'Get Git Hooks',
			value: 'getGitHooks',
			action: 'Get git hooks',
			description: 'List git hooks in a repository',
		},
		{
			name: 'Get',
			value: 'get',
			action: 'Get a webhook',
			description: 'Get a webhook in a repository by ID',
		},
		{
			name: 'Get Many',
			value: 'getAll',
			action: 'Get webhooks in a repository',
			description: 'Get webhooks in a repository',
		},
		{
			name: 'Test',
			value: 'test',
			action: 'Test a webhook',
			description: 'Trigger a webhook test delivery',
		},
		{
			name: 'Update Git Hook',
			value: 'updateGitHook',
			action: 'Update a git hook',
			description: 'Edit a git hook in a repository',
		},
		{
			name: 'Update',
			value: 'update',
			action: 'Update a webhook',
			description: 'Update a webhook in a repository',
		},
	],
	activitypub: [
		{
			name: 'Get Instance Actor',
			value: 'getInstanceActor',
			action: 'Get instance actor',
			description: 'Get the instance ActivityPub actor',
		},
		{
			name: 'Get Person',
			value: 'getPerson',
			action: 'Get a person',
			description: 'Get the ActivityPub representation of a user',
		},
		{
			name: 'Get Person Activity',
			value: 'getPersonActivity',
			action: 'Get a person activity',
			description: 'Get a specific ActivityPub activity of a user',
		},
		{
			name: 'Get Person Activity Note',
			value: 'getPersonActivityNote',
			action: 'Get a person activity note',
			description: 'Get the note for a specific ActivityPub activity of a user',
		},
		{
			name: 'Get Person Feed',
			value: 'getPersonFeed',
			action: "Get a person's feed",
			description: 'Get the ActivityPub outbox (feed) of a user',
		},
		{
			name: 'Get Repository',
			value: 'getRepository',
			action: 'Get a repository',
			description: 'Get the ActivityPub representation of a repository',
		},
		{
			name: 'Instance Actor Inbox',
			value: 'instanceActorInbox',
			action: 'Send to instance actor inbox',
			description: 'Send an ActivityPub activity to the instance actor inbox',
		},
		{
			name: 'Instance Actor Outbox',
			value: 'instanceActorOutbox',
			action: 'Send to instance actor outbox',
			description: 'Send an ActivityPub activity to the instance actor outbox',
		},
		{
			name: 'Person Inbox',
			value: 'personInbox',
			action: 'Send to person inbox',
			description: "Send an ActivityPub activity to a user's inbox",
		},
		{
			name: 'Repository Inbox',
			value: 'repositoryInbox',
			action: 'Send to repository inbox',
			description: "Send an ActivityPub activity to a repository's inbox",
		},
		{
			name: 'Repository Outbox',
			value: 'repositoryOutbox',
			action: 'Send to repository outbox',
			description: "Send an ActivityPub activity to a repository's outbox",
		},
	],
	miscellaneous: [
		{
			name: 'Get Gitignore Template',
			value: 'getGitignoreTemplate',
			action: 'Get a gitignore template',
			description: 'Get a specific gitignore template by name',
		},
		{
			name: 'Get Gitignore Templates',
			value: 'getGitignoreTemplates',
			action: 'Get gitignore templates',
			description: 'Get a list of all gitignore templates',
		},
		{
			name: 'Get Label Template',
			value: 'getLabelTemplate',
			action: 'Get a label template',
			description: 'Get a specific label template by name',
		},
		{
			name: 'Get Label Templates',
			value: 'getLabelTemplates',
			action: 'Get label templates',
			description: 'Get a list of all label templates',
		},
		{
			name: 'Get License Template',
			value: 'getLicenseTemplate',
			action: 'Get a license template',
			description: 'Get a specific license template by name',
		},
		{
			name: 'Get License Templates',
			value: 'getLicenseTemplates',
			action: 'Get license templates',
			description: 'Get a list of all license templates',
		},
		{
			name: 'Get Node Info',
			value: 'getNodeInfo',
			action: 'Get node info',
			description: 'Get the NodeInfo of the Gitea/Forgejo instance',
		},
		{
			name: 'Get Signing Key (GPG)',
			value: 'getSigningKey',
			action: 'Get signing key (GPG)',
			description: 'Get the GPG signing key of the instance',
		},
		{
			name: 'Get SSH Signing Key',
			value: 'getSSHSigningKey',
			action: 'Get SSH signing key',
			description: 'Get the SSH signing key of the instance',
		},
		{
			name: 'Get Version',
			value: 'getVersion',
			action: 'Get version',
			description: 'Get the version of the Gitea/Forgejo instance',
		},
		{
			name: 'Render Markdown',
			value: 'renderMarkdown',
			action: 'Render markdown',
			description: 'Render a markdown document as HTML',
		},
		{
			name: 'Render Markdown Raw',
			value: 'renderMarkdownRaw',
			action: 'Render markdown raw',
			description: 'Render raw markdown as HTML',
		},
		{
			name: 'Render Markup',
			value: 'renderMarkup',
			action: 'Render markup',
			description: 'Render a markup document as HTML',
		},
	],
	notification: [
		{
			name: 'Get List',
			value: 'getList',
			action: 'Get notification list',
			description: 'Get the authenticated user notification list',
		},
		{
			name: 'Get New Available',
			value: 'getNewAvailable',
			action: 'Check for new notifications',
			description: 'Check if unread notifications exist',
		},
		{
			name: 'Get Repository List',
			value: 'getRepoList',
			action: 'Get repository notification list',
			description: 'Get the notification list for a specific repository',
		},
		{
			name: 'Get Thread',
			value: 'getThread',
			action: 'Get a notification thread',
			description: 'Get a specific notification thread by ID',
		},
		{
			name: 'Mark List as Read',
			value: 'readList',
			action: 'Mark notification list as read',
			description: 'Mark the authenticated user notification list as read',
		},
		{
			name: 'Mark Repository List as Read',
			value: 'readRepoList',
			action: 'Mark repository notification list as read',
			description: 'Mark all notifications in a repository as read',
		},
		{
			name: 'Mark Thread as Read',
			value: 'readThread',
			action: 'Mark a notification thread as read',
			description: 'Mark a specific notification thread as read',
		},
	],
	package: [
		{
			name: 'Delete',
			value: 'delete',
			action: 'Delete a package',
			description: 'Delete a package from the registry',
		},
		{
			name: 'Get',
			value: 'get',
			action: 'Get a package',
			description: 'Get a specific package',
		},
		{
			name: 'Get Files',
			value: 'getFiles',
			action: 'Get package files',
			description: 'Get files associated with a package',
		},
		{
			name: 'Link to Repository',
			value: 'linkRepo',
			action: 'Link package to repository',
			description: 'Link a package to a repository',
		},
		{
			name: 'List',
			value: 'list',
			action: 'List packages',
			description: 'List packages owned by a user or organization',
		},
		{
			name: 'Unlink From Repository',
			value: 'unlinkRepo',
			action: 'Unlink package from repository',
			description: 'Unlink a package from a repository',
		},
	],
	settings: [
		{
			name: 'Get API Settings',
			value: 'getAPISettings',
			action: 'Get API settings',
			description: 'Get the API settings of the instance',
		},
		{
			name: 'Get Attachment Settings',
			value: 'getAttachmentSettings',
			action: 'Get attachment settings',
			description: 'Get the attachment settings of the instance',
		},
		{
			name: 'Get Repository Settings',
			value: 'getRepositorySettings',
			action: 'Get repository settings',
			description: 'Get the repository settings of the instance',
		},
		{
			name: 'Get UI Settings',
			value: 'getUISettings',
			action: 'Get UI settings',
			description: 'Get the UI settings of the instance',
		},
	],
};

export async function getOperations(this: ILoadOptionsFunctions): Promise<INodePropertyOptions[]> {
	const resource = this.getCurrentNodeParameter('resource') as string;

	return operationsByResource[resource] ?? [];
}
